default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  host: <%= ENV['DB_PORT_3306_TCP_ADDR'] %>

development:
  <<: *default
  database: butler_development

test:
  <<: *default
  database: butler_test

production:
  <<: *default
  database: butler_production
  username: butler
  password: <%= ENV['BUTLER_DATABASE_PASSWORD'] %>
